# -*- coding: utf-8 -*-
"""pelak.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDC0Vr1T42rbQnFCQbvIY6kgQtxOahMB
"""

!pip install ultralytics opencv-python matplotlib

from google.colab import files

# آپلود مدل آموزش‌دیده
uploaded = files.upload()

!pip install ultralytics

from google.colab import files
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt
import os

# آپلود فایل از کامپیوتر
uploaded = files.upload()

# بارگذاری مدل YOLO
model = YOLO('license_plate_detector.pt')  # نام مدل آپلودی شما

# لیست فایل‌های تصویری
image_files = [f for f in uploaded.keys() if f.lower().endswith(('.jpg', '.png', '.jpeg'))]

# اجرای مدل روی تصاویر آپلود شده
for image_path in image_files:
    results = model(image_path)[0]

    # فقط اگر پلاکی شناسایی شده باشد
    if len(results.boxes) > 0:
        img = cv2.imread(image_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # رسم باکس‌ها روی تصویر
        for box in results.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            conf = float(box.conf[0])
            cls = int(box.cls[0])
            label = f'{model.names[cls]} {conf:.2f}'
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(img, label, (x1, y1 - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

        # نمایش تصویر با پلاک شناسایی‌شده
        plt.figure(figsize=(10, 6))
        plt.imshow(img)
        plt.axis('off')
        plt.title(f'پلاک شناسایی شد: {image_path}')
        plt.show()